### ISSUE TITLE
V2 - Crash: Unlocked Door, Find Weapon

### ISSUE THREAD

**Issue by brando56894** [brando56894/dungeon-quest#19]
```
You found a locked door...

You opened it with the key that you found
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    menu(new_player)
  File "main.py", line 108, in menu
    choices[choice](player)
  File "/mnt/c/Users/bran/dungeon-quest/actions.py", line 49, in roll_dice
    find_weapon(player)
  File "/mnt/c/Users/bran/dungeon-quest/actions.py", line 105, in find_weapon
    weapon_list += weapon_type.keys()
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by brando56894** [comment]
I fixed a reference to a property that didn't exist and fixed a typo but it still doesn't work... https://github.com/brando56894/dungeon-quest/commit/0e419223900cad52b246ca5fe251a49929bddf8a

```
You found a locked door...

You opened it with the key that you found
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    menu(new_player)
  File "main.py", line 108, in menu
    choices[choice](player)
  File "/mnt/c/Users/bran/dungeon-quest/actions.py", line 49, in roll_dice
    find_weapon(player)
  File "/mnt/c/Users/bran/dungeon-quest/actions.py", line 101, in find_weapon
    weapon_list.remove(cannot_see)
ValueError: list.remove(x): x not in list
```
