### ISSUE TITLE
String Substitution Bug in Actions.py

### ISSUE THREAD

**Issue by brando56894** [brando56894/dungeon-quest#4]
After I merged in your pull requests, it now throws an error at line 97 in actions.py and I can't figure why. Here's the chunk of code

```
def visit_shop(Player):
    clearscreen()
    print ("\nWhat would you like to purchase?\n"
            "You currently have %d gold coins.\n"
            "\nP) Health Potions\n""W) Weapons\n"
            "N) Nothing/Leave Store", %(Player.gold))
```

Here's the error:

```
[bran@archvm]: ~/dungeon-quest>$ python2 main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import actions
  File "/home/bran/dungeon-quest/actions.py", line 97
    "N) Nothing/Leave Store", %(Player.gold))
                                                        ^
SyntaxError: invalid syntax
```

**Comment by ghost** [comment]
Remove the comma before %(Player.gold), and that should do it. Sorry about that.

**Comment by brando56894** [comment]
Haha I was comparing it to other substitution lines and completely missed that.
